const MAIN = 'A. Основные ветки алгоритма';
const BUTTON = 'B. Какую кнопку нажать';

export default [
  {
    id: 'c1', group: MAIN,
    title: 'Одно поле и кнопка отправки',
    expect: 'submit',
    code: 'input-keydown-enter fu-mimic-button fu-mimic-disabled btn-click',
    expectText: '<code>click()</code> по кнопке → кнопка вызывает <code>requestSubmit()</code> → <code>submit</code>',
    why: 'Шаг 2 находит <code>x-button[type=submit]</code>, шаг 3 нажимает её, и <code>mimicFormEnterBehavior</code> возвращает <code>true</code>. Обработчик возвращает <code>false</code>, FAST отменяет keydown, поэтому нативного <code>change</code> по Enter нет. Если вписать текст, <code>change</code> придёт только при потере фокуса (сравните с кейсом 17).',
    markup: `<form id="c1-form"><x-input id="c1-name" data-primary placeholder="Имя"></x-input><x-button id="c1-save" type="submit">Сохранить</x-button></form>`,
  },
  {
    id: 'c2', group: MAIN,
    title: 'Одно поле, кнопок нет',
    expect: 'submit',
    code: 'fu-mimic-count fu-isSubmitBlocking input-flag',
    expectText: '<code>form.requestSubmit()</code> → <code>submit</code> с <code>submitter = null</code>',
    why: 'Кнопки нет, поэтому шаг 4 считает текстовые поля. Поле одно — отправляем, как браузер отправляет форму с единственным <code>&lt;input&gt;</code>.',
    markup: `<form id="c2-form"><x-input id="c2-search" data-primary placeholder="Поиск"></x-input></form>`,
  },
  {
    id: 'c3', group: MAIN,
    title: 'Два поля, кнопок нет',
    expect: 'none',
    code: 'fu-mimic-count fu-mimic-false input-keydown-enter',
    expectText: 'ничего не происходит, keydown не отменяется',
    why: 'Полей больше одного, кнопки нет — браузер в такой форме ничего не делает. <code>mimicFormEnterBehavior</code> возвращает <code>false</code>, обработчик — <code>true</code>, и keydown остаётся неотменённым.',
    markup: `<form id="c3-form"><x-input id="c3-login" data-primary placeholder="Логин"></x-input><x-input id="c3-password" type="password" placeholder="Пароль"></x-input></form>`,
  },
  {
    id: 'c4', group: MAIN,
    title: 'Наше поле + нативный input, кнопок нет',
    expect: 'none',
    code: 'fu-isSubmitBlocking fu-types input-flag',
    expectText: 'ничего не происходит',
    why: 'Нативный <code>input[type=text]</code> тоже считается текстовым полем, всего полей два. Соседи в форме учитываются одинаково, наши они или нативные.',
    markup: `<form id="c4-form"><x-input id="c4-city" data-primary placeholder="Город"></x-input><input id="c4-street" placeholder="Улица (нативный)"></form>`,
  },
  {
    id: 'c5', group: MAIN,
    title: 'Поле + checkbox, select, textarea, hidden',
    expect: 'submit',
    code: 'fu-types fu-isSubmitBlocking',
    expectText: '<code>form.requestSubmit()</code> → <code>submit</code>',
    why: 'Checkbox, select, textarea и hidden нет в списке <code>submitBlockingInputTypes</code>, поэтому считается только наше поле.',
    markup: `<form id="c5-form"><x-input id="c5-email" data-primary type="email" placeholder="Email"></x-input><label><input type="checkbox" id="c5-agree"> согласен</label><select id="c5-lang"><option>RU</option><option>EN</option></select><textarea id="c5-note" rows="1" placeholder="Комментарий"></textarea><input type="hidden" id="c5-token" value="1"></form>`,
  },
  {
    id: 'c6', group: BUTTON,
    title: 'Нативная кнопка без type стоит раньше нашей',
    expect: 'submit',
    code: 'fu-isSubmitButton fu-getDefaultButton',
    expectText: '<code>click()</code> по нативной кнопке → <code>submit</code> с <code>submitter</code> = эта кнопка',
    why: '<code>&lt;button&gt;</code> без <code>type</code> — это submit-кнопка (<code>type === \'submit\'</code>). Кнопка по умолчанию — первая по порядку в документе, неважно, наша она или нативная.',
    markup: `<form id="c6-form"><x-input id="c6-query" data-primary placeholder="Запрос"></x-input><button id="c6-native">Нативная</button><x-button id="c6-custom" type="submit">Наша</x-button></form>`,
  },
  {
    id: 'c7', group: BUTTON,
    title: 'Кнопка вне формы с атрибутом form',
    expect: 'submit',
    code: 'fu-getDefaultButton',
    expectText: '<code>click()</code> по внешней кнопке',
    why: '<code>form.elements</code> включает и элементы с <code>form="id"</code>, в порядке документа. Внешняя кнопка стоит раньше внутренней.',
    markup: `<x-button id="c7-outside" type="submit" form="c7-form">Снаружи (form="c7-form")</x-button><form id="c7-form"><x-input id="c7-title" data-primary placeholder="Заголовок"></x-input><x-button id="c7-inside" type="submit">Внутри</x-button></form>`,
  },
  {
    id: 'c8', group: BUTTON,
    title: 'Первая кнопка disabled, вторая активна',
    expect: 'none',
    code: 'fu-mimic-button fu-mimic-disabled btn-disabled',
    expectText: 'ничего не происходит, но keydown отменяется',
    why: 'Кнопка по умолчанию — первая, даже неактивная. Не кликаем и вторую не ищем, как и браузер. Но <code>mimicFormEnterBehavior</code> всё равно возвращает <code>true</code>, поэтому keydown отменяется.',
    markup: `<form id="c8-form"><x-input id="c8-code" data-primary placeholder="Код"></x-input><x-button id="c8-disabled" type="submit" disabled>Отправить (disabled)</x-button><x-button id="c8-enabled" type="submit">Черновик</x-button></form>`,
  },
  {
    id: 'c9', group: BUTTON,
    title: 'Первая кнопка внутри <fieldset disabled>',
    expect: 'none',
    code: 'fu-mimic-disabled',
    expectText: 'ничего не происходит',
    why: 'Атрибута <code>disabled</code> на кнопке нет, её выключает fieldset. <code>:disabled</code> это учитывает, а свойство <code>.disabled</code> — нет, поэтому в коде именно <code>matches(\':disabled\')</code>.',
    markup: `<form id="c9-form"><fieldset disabled><x-button id="c9-fieldset" type="submit">В fieldset</x-button></fieldset><x-input id="c9-phone" data-primary type="tel" placeholder="Телефон"></x-input><x-button id="c9-ok" type="submit">Ок</x-button></form>`,
  },
  {
    id: 'c10', group: BUTTON,
    title: 'Кнопка скрыта (hidden)',
    expect: 'submit',
    code: 'fu-getDefaultButton fu-mimic-disabled',
    expectText: '<code>click()</code> по скрытой кнопке → <code>submit</code>',
    why: 'Видимость не проверяется — браузер тоже нажимает скрытую кнопку. Подсчёт полей нужен, только когда кнопок нет, поэтому два поля не мешают. Кнопка с атрибутом <code>hidden</code> в форме есть, но её не видно.',
    markup: `<form id="c10-form"><x-input id="c10-from" data-primary placeholder="Откуда"></x-input><x-input id="c10-to" placeholder="Куда"></x-input><x-button id="c10-hidden" type="submit" hidden>Скрытая</x-button></form>`,
  },
];
